// <auto-generated />
namespace PhoneCat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class onetomany_images : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(onetomany_images));
        
        string IMigrationMetadata.Id
        {
            get { return "201702161236334_one-to-many_images"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
